In [2]:
import os
from pathlib import Path

os.getcwd()
mb_dir = Path(os.getcwd()).parent.parent
os.chdir(mb_dir)
data_dir = str(mb_dir.parent / "data")
root_dir = str(mb_dir.parent)

import xarray as xr
import scipy.io as sio
import numpy as np


### Fig 1

In [33]:
file_30day_r = f"{root_dir}/fig_data/deterministic_scores_15_day_2019_2024.mat"
data_30_r = sio.loadmat(file_30day_r)

print(data_30_r.keys())
print(data_30_r["mae_cmz_fixed_clim"])
print(data_30_r["std_er_fixed_clim"])
print(['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
print(data_30_r['mae_cmz_mean_15'])
data_30_r["mae_avg_15"][:,:,1].transpose()


dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_15', 'far_cmz_mean_15', 'lat', 'lon', 'mae_avg_15', 'mae_cmz_fixed_clim', 'mae_cmz_mean_15', 'mae_yr_15', 'miss_rate_15', 'mr_cmz_mean_15', 'std_er_15', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']
[[5.68293651 3.79627425 3.9192328  3.13102183 4.49211052 3.06161155
  3.75384149 3.38844346]]


array([[        nan,         nan,  3.53333333, 34.99069688,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  5.05571429,  7.77878788,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  3.27619048,  3.67222222,  3.93333333,  6.06928571,
                nan,         nan,         nan,         nan],
       [ 3.88888889,  2.51666667,  4.18      ,  2.27666667,  1.95666667,
         5.6769697 ,         nan,         nan,         nan],
       [ 2.36666667,  2.625     ,  5.55166667,  2.67666667,  2.97380952,
         7.14285714,  1.55      ,  3.82357143,         nan],
       [ 6.86111111,  4.75      ,  7.08944444,  3.79444444,  4.3       ,
         2.5       ,  2.11666667,  2.21666667,         nan],
       [        nan, 21.7169697 , 11.75      ,  5.38333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,   

In [27]:
file_30day = f"{root_dir}/output/deterministic_scores_15_day_2019_2024.mat"
data_30 = sio.loadmat(file_30day)

print(data_30.keys())
print(data_30["mae_cmz_fixed_clim"])
print(data_30["std_er_fixed_clim"])
print(['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
print(data_30['mae_cmz_mean_15'])
data_30["mae_avg_15"][:,:,1].transpose()

dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_15', 'far_cmz_mean_15', 'lat', 'lon', 'mae_avg_15', 'mae_cmz_fixed_clim', 'mae_cmz_mean_15', 'mae_yr_15', 'miss_rate_15', 'mr_cmz_mean_15', 'std_er_15', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']
[[5.68293651 3.7564515  4.02335538 3.09977183 4.60825103 3.09661265
  3.47638889 3.31666597]]


array([[        nan,         nan,  3.57777778, 35.0709023 ,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  4.67571429,  7.69350649,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  2.79047619,  3.59444444,  3.8       ,  6.08214286,
                nan,         nan,         nan,         nan],
       [ 4.        ,  2.5       ,  4.02333333,  2.44333333,  1.93666667,
         5.80606061,         nan,         nan,         nan],
       [ 2.46666667,  2.47142857,  5.675     ,  2.91666667,  2.91666667,
         7.05142857,  1.78      ,  3.97428571,         nan],
       [ 6.88888889,  5.5       ,  6.97777778,  3.73333333,  4.13071429,
         3.        ,  2.41666667,  2.26666667,         nan],
       [        nan, 21.50161616, 11.88333333,  5.36666667,         nan,
                nan,         nan,         nan,         nan],
       [        nan, 13.        ,         nan,         nan,   

In [30]:
data_30["mae_avg_15"][:,:,1].transpose()

array([[        nan,         nan,  3.57777778, 35.0709023 ,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  4.67571429,  7.69350649,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  2.79047619,  3.59444444,  3.8       ,  6.08214286,
                nan,         nan,         nan,         nan],
       [ 4.        ,  2.5       ,  4.02333333,  2.44333333,  1.93666667,
         5.80606061,         nan,         nan,         nan],
       [ 2.46666667,  2.47142857,  5.675     ,  2.91666667,  2.91666667,
         7.05142857,  1.78      ,  3.97428571,         nan],
       [ 6.88888889,  5.5       ,  6.97777778,  3.73333333,  4.13071429,
         3.        ,  2.41666667,  2.26666667,         nan],
       [        nan, 21.50161616, 11.88333333,  5.36666667,         nan,
                nan,         nan,         nan,         nan],
       [        nan, 13.        ,         nan,         nan,   

### Figure 3: Bin size issues

In [31]:
data_30_r["mae_avg_15"][:,:,1].transpose()

array([[        nan,         nan,  3.53333333, 34.99069688,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  5.05571429,  7.77878788,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  3.27619048,  3.67222222,  3.93333333,  6.06928571,
                nan,         nan,         nan,         nan],
       [ 3.88888889,  2.51666667,  4.18      ,  2.27666667,  1.95666667,
         5.6769697 ,         nan,         nan,         nan],
       [ 2.36666667,  2.625     ,  5.55166667,  2.67666667,  2.97380952,
         7.14285714,  1.55      ,  3.82357143,         nan],
       [ 6.86111111,  4.75      ,  7.08944444,  3.79444444,  4.3       ,
         2.5       ,  2.11666667,  2.21666667,         nan],
       [        nan, 21.7169697 , 11.75      ,  5.38333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,   

In [ ]:
clim_df_15, clim_onset_15 = c_metrics.compute_climatology_baseline_multiple_years(
    years=config["years"],
    imd_folder=config["imd_folder"],
    thres_file=config["thres_file"],
    tolerance_days=3,
    verification_window=1, #
    forecast_days=15,
    max_forecast_day=15,
    mok=True,
    onset_window=5,
    mok_month=6,
    mok_day=2,
)