In [2]:
import os
from pathlib import Path

os.getcwd()
mb_dir = Path(os.getcwd()).parent.parent
os.chdir(mb_dir)
data_dir = str(mb_dir.parent / "data")
root_dir = str(mb_dir.parent)

import xarray as xr
import scipy.io as sio
import numpy as np


### Fig 1

In [89]:
file_30day_r = f"{root_dir}/fig_data/deterministic_scores_15_day_2019_2024.mat"
data_30_r = sio.loadmat(file_30day_r)

print(data_30_r.keys())
print(data_30_r["mae_cmz_fixed_clim"])
print(data_30_r["std_er_fixed_clim"])
print(data_30_r['mr_cmz_mean_15'])
print(['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
data_30_r["mae_avg_15"][:,:,3].transpose()


dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_15', 'far_cmz_mean_15', 'lat', 'lon', 'mae_avg_15', 'mae_cmz_fixed_clim', 'mae_cmz_mean_15', 'mae_yr_15', 'miss_rate_15', 'mr_cmz_mean_15', 'std_er_15', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
[[41.67122507 19.50734049 18.40854701 41.18347578 14.82393162 30.10655271
  30.06410256 25.5008547 ]]
['IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']


array([[        nan,         nan,  5.43333333, 37.23333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  6.6       ,  7.6       ,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  5.5       ,  4.05      ,  1.125     ,  4.86111111,
                nan,         nan,         nan,         nan],
       [ 1.33333333,  7.        ,  2.86944444,  2.25833333,  2.09166667,
         5.51666667,         nan,         nan,         nan],
       [ 4.55555556,  0.66666667,  3.86666667,  4.13611111,  2.24206349,
         4.68525132,  2.46666667,  4.74742063,         nan],
       [ 1.5       , 12.        ,  4.4       ,  3.18888889,  4.07777778,
         2.        ,  2.725     ,  3.07222222,         nan],
       [        nan, 18.97333333, 16.25      ,         nan,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,   

In [84]:
file_30day = f"{root_dir}/output/deterministic_scores_30_day_2004_2021.mat"
data_30 = sio.loadmat(file_30day)

print(data_30.keys())
print(data_30["mae_cmz_fixed_clim"])
print(data_30["std_er_fixed_clim"])
print(["Clim", 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'])
print(data_30['mae_cmz_mean_30'].shape)
data_30["mae_avg_30"][:,:,3].transpose()

dict_keys(['__header__', '__version__', '__globals__', 'false_alarm_30', 'far_cmz_mean_30', 'lat', 'lon', 'mae_avg_30', 'mae_cmz_fixed_clim', 'mae_cmz_mean_30', 'mae_yr_30', 'miss_rate_30', 'mr_cmz_mean_30', 'std_er_30', 'std_er_fixed_clim'])
[[7.18333333]]
[[0.9686474]]
['Clim', 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM']
(1, 8)


array([[        nan,         nan,  6.70833333, 43.58666667,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  6.26041667, 14.50784314,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  5.32941176,  5.39920635, 11.52491182,  7.26499118,
                nan,         nan,         nan,         nan],
       [10.27916667, 11.01322751,  9.13048541,  6.51481481,  6.20251323,
         9.28541667,         nan,         nan,         nan],
       [17.32820391,  8.71216931,  6.56190476,  7.45245098,  5.4929972 ,
         5.55223214,  3.71568627,  7.93823529,         nan],
       [17.76428571, 14.81289683, 11.9755291 ,  6.81904762,  7.17955182,
        20.82142857,  7.13406085,  6.53740079,         nan],
       [        nan, 27.06439394, 18.41388889,         nan,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,   

In [83]:
model_num=7
print(["Clim", 'IFS', 'AIFS', 'FuXi', 'Graphcast', 'GenCast', 'FuXi-S2S', 'NGCM'][model_num])
data_30["mae_cmz_mean_30"][0][model_num] - data_30_r["mae_cmz_mean_30"][0][model_num]

NGCM


IndexError: index 7 is out of bounds for axis 0 with size 7

In [31]:
data_30_r["mae_avg_15"][:,:,1].transpose()

array([[        nan,         nan,  3.53333333, 34.99069688,         nan,
                nan,         nan,         nan,         nan],
       [        nan,         nan,  5.05571429,  7.77878788,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  3.27619048,  3.67222222,  3.93333333,  6.06928571,
                nan,         nan,         nan,         nan],
       [ 3.88888889,  2.51666667,  4.18      ,  2.27666667,  1.95666667,
         5.6769697 ,         nan,         nan,         nan],
       [ 2.36666667,  2.625     ,  5.55166667,  2.67666667,  2.97380952,
         7.14285714,  1.55      ,  3.82357143,         nan],
       [ 6.86111111,  4.75      ,  7.08944444,  3.79444444,  4.3       ,
         2.5       ,  2.11666667,  2.21666667,         nan],
       [        nan, 21.7169697 , 11.75      ,  5.38333333,         nan,
                nan,         nan,         nan,         nan],
       [        nan,  0.        ,         nan,         nan,   

### Figure 3

In [36]:
import scipy.io as sio
weekly_file = f"{root_dir}/fig_data/5day_forecastwindow_cmz_2019_2024.mat"
data = sio.loadmat(weekly_file)
mae_cmz = data['mae_cmz']  # Shape should be (6, 8) for 6 time periods, 8 models
far_cmz = data['far_cmz']  # Shape should be (6, 8)
mr_cmz = data['mr_cmz']    # Shape should be (4, 8) for 4 weeks
std_er = data['std_er']    # Standard errors for MAE

print(data["model_str"])
far_cmz

[[array(['clim'], dtype='<U4')]
 [array(['ifs'], dtype='<U3')]
 [array(['aifs'], dtype='<U4')]
 [array(['fuxi'], dtype='<U4')]
 [array(['graphcast'], dtype='<U9')]
 [array(['gencast'], dtype='<U7')]
 [array(['fuxis2s'], dtype='<U7')]
 [array(['ngcm51'], dtype='<U6')]]


array([[ 5.00552672,  5.14806667,  6.14221866,  1.61055272,  8.92096044,
         4.60774198,  3.59489348,  5.85507257],
       [ 7.95982277,  8.78547899,  8.85290505,  4.26848899, 11.39773605,
         6.4457009 ,  6.9739043 ,  7.40127785],
       [10.5148626 ,  7.35800489, 12.77523487,  6.54565838, 13.09821372,
         4.49552206,  6.85812311,  4.00694431],
       [12.0407337 ,  6.28736664, 12.38162626, 13.88521342, 24.13860657,
         6.12166779, 11.62840659,  6.82676204],
       [14.46997348,  7.46808236, 17.49078923, 15.73044724, 27.4567295 ,
         6.41197107, 11.71757763, 10.33545782],
       [16.13182367, 10.74482817, 23.85337689, 20.23400135, 17.59355116,
         9.77286226, 18.68398268,  6.96542738]])